### ISSUE TITLE
add dark theme

### ISSUE THREAD

**Issue by lowlyw** [woboq/iquassel#12]
iQuassel should use the current native theme, weather it is dark or light. Colors of text and nick highlights should be based on this as well.

**Comment by guruz** [comment]
Re-opening as there is a few screens (and labels) still showing up in white..

**Comment by guruz** [comment]
```
<tmbg> is there a way to edit the dark theme that lowlyw created? 
<tmbg> the white channels in the list in dark mode are still pretty bright. 
<crowell> they're the colors by the "XXX not HI Complient" or something
```

**Comment by guruz** [comment]
<guruz> They could be faked
<guruz> Eg generated from another color by modifying that one

**Comment by guruz** [comment]
Fixed the colors for the disconnect and connect screens.

Just noticed iPad dark mode is not done yet hmm
