### ISSUE TITLE
Seems to lose settings sometimes (on startup)

### ISSUE THREAD

**Issue by guruz** [woboq/iquassel#14]
On startup, it comes only with a fresh screen.
Maybe somethig wrong with the PDKeychainBindings that we're using (outdated etc..)

![IMG_4302](https://user-images.githubusercontent.com/959327/71640813-a9de0000-2c91-11ea-9d30-c650bdb49fd9.png)

FYI @lowlyw

**Comment by lowlyw** [comment]
haven't experienced this, but should probably migrate to `SecItem` api

https://developer.apple.com/documentation/security/keychain_services/keychain_items

**Comment by guruz** [comment]
When I kill the app if it comes up empty and restart it, the credentials are back.
So it's a loading problem.
Maybe some security context not there yet

**Comment by guruz** [comment]
This is definitely happening more often when iphone was asleep long, e.g. in the morning.

One thing definitely to do: Save credentials only on succesful connect so we don't accidently overwrite with empty credentials

**Comment by guruz** [comment]
Fixed with above commit
