### ISSUE TITLE
App crashes almost immediately after launch

### ISSUE THREAD

**Issue by klein1jo** [woboq/iquassel#15]
The app crashes almost immediately after launch.  iPhone X running 1.8.0 on iOS 13.3.  Tried deleting app and installing fresh from App Store.

**Comment by guruz** [comment]
Thanks for reporting. Fix pushed ^^

**Comment by guruz** [comment]
The status of your (iOS) app, iQuassel for Quassel Cores, is now "Waiting For Review"

**Comment by klein1jo** [comment]
Thanks.  I had left a review before I thought of submitting an issue.  Already requested deletion.  Appreciate the updates.

**Comment by guruz** [comment]
Great!
