### ISSUE TITLE
 Stuck at "Authenticated"

### ISSUE THREAD

**Issue by guruz** [woboq/iquassel#17]
Reported several times.

@justJanne proposes this is probably because of https://github.com/woboq/iquassel/blob/6920ec29eff6ce71d439cfcda240e70ff0705b5d/quassel-for-ios/quassel-for-ios/QuasselCoreConnection.m#L478
```
<justJanne> you always send an initrequest for the bufferviewconfig with name "0" and break if that doesn’t exist
<justJanne> but the ids are chosen by creation, if a user deletes the first bufferviewconfig, and creates a new one, this won’t work anymore
<justJanne> you’ll need to have code to properly support multiple bufferviewconfigs
```

**Comment by justjanne** [comment]
In Quasseldroid we use the BufferViewManager to determine which chat lists exist, and show a dropdown to select the chat list the user wants to use at the current time:

[![Screenshot of chat list view](https://i.k8r.eu/ZsVkcw.png)](https://i.k8r.eu/ZsVkcw.png)

[![Screenshot of chat list dropdown extended](https://i.k8r.eu/JkrMUQ.png)](https://i.k8r.eu/JkrMUQ.png)

**Comment by justjanne** [comment]
The BufferViewManager has the following interface: https://quasseldroid.info/docs/protocol/serialization/signalproxy_objects/#bufferviewmanager

**Comment by guruz** [comment]
let's close this and handle BufferViewManager properly later
