### ISSUE TITLE
Tab-complete for nicks does not work on iOS devices using Smart Keyboards

### ISSUE THREAD

**Issue by phuzion** [woboq/iquassel#21]
When using the Smart Keyboard Folio for iPad, or presumably any other external keyboard, nick completion does not occur when pressing the hardware Tab key.

What does occur is a tab-complete from the predictive keyboard, which should not be the case.

**Comment by guruz** [comment]
Fix pushed, only tested with simulator though :)

**Comment by guruz** [comment]
@lowlyw FYI ^^

**Comment by phuzion** [comment]
Can confirm that this issue is resolved, using version 1.8.3 on the App Store.
