### ISSUE TITLE
Button to filter joins/parts/quits

### ISSUE THREAD

**Issue by guruz** [woboq/iquassel#4]
Note that this means to fetch more data from the server

**Comment by guruz** [comment]
(might be quite easy by return a height 0 for hidden cells/lines?)

**Comment by MrXermon** [comment]
It would be cool if we could find a solution for that. In my case, most of the screen is used by joins/parts.
![84EE3CD4-B1CC-4EFE-8738-2D8775E7C46B](https://user-images.githubusercontent.com/8172056/72201202-d217ec80-3451-11ea-8fad-6bddaf51bde1.jpeg)
